# Generated by Django 5.2.17 on 2026-09-23 23:59

import core_api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=128, unique=True)),
                ('resource', models.CharField(max_length=100)),
                ('verb', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rbac_permission',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='Given app-wide to every new user.')),
                ('grants_all', models.BooleanField(default=False, help_text='Every permission, including ones added later.')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='platform_auth.permission')),
            ],
            options={
                'db_table': 'rbac_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('scope_id', models.UUIDField(blank=True, help_text='Empty: the role applies app-wide. Set: only within that scope.', null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='platform_auth.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='platform_auth.user')),
            ],
            options={
                'verbose_name': 'role assignment',
                'db_table': 'rbac_role_assignment',
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope_id__isnull', True)), fields=('user', 'role'), name='uq_rbac_assignment_app_wide'), models.UniqueConstraint(fields=('user', 'role', 'scope_id'), name='uq_rbac_assignment_scoped')],
            },
        ),
    ]
