# Generated by Django 5.2.17 on 2026-10-01 03:18

from django.db import migrations, models
from django.db.models import F


def existing_accounts_are_verified(apps, schema_editor):
    """Accounts from before verification existed count as verified -
    turning verification on must not lock anyone out."""
    apps.get_model("platform_auth", "User").objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('platform_auth', '0003_rbac_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='ip',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user_agent',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(existing_accounts_are_verified, migrations.RunPython.noop),
    ]
